import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Switzer = localFont({
  src: "./fonts/Switzer-Variable.woff",
  variable: "--font-geist-sans", // this creates a custom CSS variable
  weight: "100 900", // specify the font weights if needed
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Switzer.variable} ${geistMono.variable} antialiased`} // Applying the font variables
      >
        {children}
      </body>
    </html>
  );
}
