import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Sora } from "next/font/google";

// Initialize the Google Font
const sora = Sora({
  subsets: ["latin"], // Define the subset for better performance
  variable: "--font-sora", // Optional: Create a custom CSS variable
  weight: ["400", "700"], // Include the font weights you need
});

// Initialize Local Fonts
const Switzer = localFont({
  src: "./fonts/Switzer-Variable.woff",
  variable: "--font-geist-sans", // Create a CSS variable for Switzer
  weight: "100 900", // Define the font weights for Switzer
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono", // Create a CSS variable for Geist Mono
  weight: "100 900", // Define the font weights for Geist Mono
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sora.variable} ${Switzer.variable} ${geistMono.variable} antialiased`} // Applying all font variables
      >
        {children}
      </body>
    </html>
  );
}
